[Network]
topology = MultiChipMesh
routing_algorithm = XY
k_node = 2
k_chip = 2
buffer_size = 20
vc_number = 2
d2d_IF = off_chip_serial

[Workload]
traffic = uniform

[Simulation]
injection_increment = 0.05
threads = 8
;   int timeout_threshold;
;   int timeout_limit;
;   int threads;
;   // Each thread fetches issue_width packets at a time
;   int issue_width;
