[Network]
topology = BasicArbitrary
routing_algorithm = NRL_routing
n_nodes = 128
buffer_size = 20
vc_number = 4
num_escape_vcs = 2
d2d_IF = off_chip_serial
adjaceny_matrix_filename = ./input/topologies/pt_2c_128r_6p_8x4x4.map
nrl_filename = ./input/routing/pt_2c_128r_6p_8x4x4_dor_dim_tiebreak.nrl2
nrl_version = 2
vc_filename = ./input/vc_alloc/pt_2c_128r_6p_8x4x4_dor_dim_tiebreak.vcmat2
vc_type = dateline
vc_version = 2

[Workload]
traffic = uniform

[Simulation]
injection_increment = 1.0
threads = 32
;   int timeout_threshold;
;   int timeout_limit;
;   int threads;
;   // Each thread fetches issue_width packets at a time
;   int issue_width;
